# Generated by Django 3.0.8 on 2020-08-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviecoll', '0002_auto_20200801_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='desc',
            new_name='description',
        ),
    ]
