# Generated by Django 3.0.8 on 2020-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecoll', '0003_auto_20200801_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=2048),
        ),
    ]
