# Generated by Django 3.0.8 on 2020-08-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecoll', '0004_auto_20200801_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(null=True, to='moviecoll.Collection'),
        ),
    ]
