# Generated by Django 3.0.8 on 2020-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecoll', '0005_auto_20200801_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(to='moviecoll.Collection'),
        ),
    ]
